version: '3.7'

services:
  editor:
    container_name: editor
    image: editor:latest
    env_file: .env
    user: "${UID}:${GID}"
    build:
      context: .
      args:
        # USER_ID: ${UID:-1000}
        # GROUP_ID: ${GID:-1000}
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        USERNAME: ${USERNAME}
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_EMAIL: ${GIT_EMAIL} 
    environment:
      UID:
      GID:
    # networks:
    #   - editor
    deploy:
      replicas: 1
    volumes:
      - "./app:/app:rw"
    entrypoint: ['/bin/zsh']
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t


# Overlay network create virtual network for multiple host
# Bridge network creates virtual network for same host
networks:
  default:
    name: "editor-network"
    driver: overlay
